apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-pipeline
  labels:
    app.kubernetes.io/name: docker-k8s-pipeline
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docker-k8s-pipeline
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docker-k8s-pipeline
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: docker-k8s-pipeline
          image: docker.io/simonnetje/docker-k8s-pipeline:c6e8c4095f77bc7730632b2455c09704b10c76b9
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_DIR
              value: /data
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: app-data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: docker-k8s-pipeline-data
