apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-k8s-pipeline-data
  labels:
    app.kubernetes.io/name: docker-k8s-pipeline
    app.kubernetes.io/component: api
spec:
  storageClassName: shared-hosting-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
