apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-pipeline
  labels:
    app.kubernetes.io/name: docker-k8s-pipeline
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docker-k8s-pipeline
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
